# Generated by Django 4.1.3 on 2022-12-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='site',
        ),
    ]
