# Generated by Django 4.1.3 on 2022-12-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceApp', '0002_remove_contact_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='site',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
